In [14]:
import gym
import numpy as np
import pandas as pd
import time
import pickle

In [15]:
env = gym.make('FrozenLake-v0')

epsilon = 0.9
# min_epsilon = 0.1
# max_epsilon = 1.0
# decay_rate = 0.01

total_episodes = 10000
max_steps = 100

lr_rate = 0.81
gamma = 0.96

Q = np.zeros((env.observation_space.n, env.action_space.n))
    
def choose_action(state):
    action=0
    if np.random.uniform(0, 1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q[state, :])
    return action

def learn(state, state2, reward, action):
    predict = Q[state, action]
    target = reward + gamma * np.max(Q[state2, :])
    Q[state, action] = Q[state, action] + lr_rate * (target - predict)


In [18]:
# Start
rewards=0

for episode in range(total_episodes):
    state = env.reset()
    t = 0
    
    while t < max_steps:
        # env.render()

        action = choose_action(state)  

        state2, reward, done, info = env.step(action)  

        learn(state, state2, reward, action)

        state = state2

        t += 1
        rewards+=1
        if done:
            break
#     epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode) 

    
print ("Score over time: ", rewards/total_episodes)
print(Q)

Score over time:  7.8407
[[6.57704419e-01 6.29738546e-01 6.37444467e-01 6.29926737e-01]
 [6.24746837e-01 4.40875827e-03 5.06910694e-01 6.47145481e-01]
 [6.11100472e-01 7.07598594e-01 6.87193973e-01 5.89996315e-01]
 [1.15428929e-01 5.89266136e-01 5.88285101e-01 6.13702100e-01]
 [7.00685368e-01 6.93060817e-01 6.20714152e-01 4.41601946e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.83989084e-01 2.30855832e-02 7.36295655e-01 1.39259500e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.71902551e-01 7.40678545e-01 6.53343830e-01 7.23161986e-01]
 [1.44094529e-01 8.08347110e-01 7.48542184e-01 6.63653899e-01]
 [7.59345936e-01 1.52925363e-01 6.90762400e-01 2.66184051e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.50648437e-01 8.10019867e-01 7.93601817e-01 1.52353413e-01]
 [8.43586024e-01 9.32944520e-01 9.10073202e-01 9.80912107e-01]
 [0.00000000e+00 0.00000000e+0

In [19]:
map = []
for i in range(16):
    map.append(np.argmax(Q[i, :]))
act = {0:"L", 1:"D", 2:"R", 3:"U"}
for i in range(len(map)):
    print(act[map[i]], end=' ')
    if (i+1)%4==0:
        print('\n')
    
# pd.to_pickle(QT.Q, "frozenLake_qTable.pkl")
with open("frozenLake_qTable.pkl", 'wb') as f:
    pickle.dump(Q, f)

print("DONE !!!")


L U D U 

L L R L 

D D L L 

L D U L 

DONE !!!


In [ ]:
rewards